"""
CellRank Visualization
Visualize cell fate and lineage results from CellRank analysis
"""

import streamlit as st
import scanpy as sc
import scvelo as scv
import cellrank as cr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import io
import time
from helper_func import clear_old_directories, clear_old_files
from streamlit_sortables import sort_items

@st.cache_data
def create_cell_color_mapping(cell_list, palette_name):
    """
    Function to create consistent mapping between cell names/clusters/states and colors

    Parameters
    ----------
    cell_list : list
        List of cell names/cluster names/state names
    palette_name : str
        Name of discrete color palette to use

    Returns
    -------
    dict
        Dictionary with cell names/cluster names/state names as keys and colors as values
    """
    n_cells = len(cell_list)
    base_palette = sns.color_palette(palette_name)
    base_n = len(base_palette)

    if n_cells <= base_n:
        colors = base_palette[:n_cells]
    else:
        colors = sns.color_palette(palette_name, n_colors=n_cells)

    return {cell: color for cell, color in zip(cell_list, colors)}

st.set_page_config(page_title="CellRank Visualization", page_icon="🎯", layout="wide")

st.title("🎯 CellRank Visualization")
st.markdown("""
Visualize CellRank analysis results.

### Visualization Types
1. **Terminal states**: UMAP display of terminal states
2. **Fate probabilities**: Fate probability to each terminal state
3. **Initial states**: Initial states (if calculated)
4. **Fate probability heatmap**: Heatmap of fate probabilities
5. **Gene trends**: Gene expression trends along lineage

### Reference
- [CellRank Visualization](https://cellrank.readthedocs.io/en/stable/api.html#plotting)
""")

# Initialize session state
if "cellrank_vis_temp_dir" not in st.session_state:
    cellrank_vis_temp_dir = os.path.join("temp", f"cellrank_vis_{round(time.time())}")
    os.makedirs("temp", exist_ok=True)
    clear_old_directories("temp")
    clear_old_files("temp")
    os.makedirs(cellrank_vis_temp_dir, exist_ok=True)
    st.session_state.cellrank_vis_temp_dir = cellrank_vis_temp_dir
else:
    cellrank_vis_temp_dir = st.session_state.cellrank_vis_temp_dir

# ========================================
# Step 1: Upload file
# ========================================
st.header("Step 1: Upload CellRank result")

uploaded_h5ad = st.file_uploader(
    "Upload h5ad file (CellRank result)",
    type=['h5ad'],
    key="cellrank_vis_h5ad_upload",
    help="h5ad file generated by CellRank analysis app"
)

if uploaded_h5ad is not None:
    st.success("✓ File uploaded")

    # Load data
    if ("cellrank_vis_adata" not in st.session_state or
        st.session_state.get("cellrank_vis_uploaded_file") != uploaded_h5ad.name):

        with st.spinner("Loading data..."):
            # Save uploaded file temporarily
            temp_h5ad_path = os.path.join(cellrank_vis_temp_dir, "input.h5ad")
            with open(temp_h5ad_path, "wb") as f:
                f.write(uploaded_h5ad.read())

            # Read data with error handling for malformed h5ad
            try:
                adata = sc.read_h5ad(temp_h5ad_path)
            except ValueError as e:
                if "Data must be 1-dimensional" in str(e):
                    st.warning("⚠️ Detected malformed metadata in h5ad file. Attempting to fix...")

                    # Try to read with backed mode and fix the issue
                    try:
                        import h5py
                        import anndata as ad

                        # Read with backed mode
                        adata_backed = ad.read_h5ad(temp_h5ad_path, backed='r')

                        # Copy data layer by layer to avoid metadata issues
                        try:
                            X_data = adata_backed.X[:]
                        except:
                            X_data = adata_backed.X

                        # Copy obsm without problematic entries
                        obsm_dict = {}
                        for key in adata_backed.obsm.keys():
                            try:
                                obsm_dict[key] = adata_backed.obsm[key][:]
                            except:
                                st.warning(f"Skipping obsm['{key}'] due to read error")

                        # Copy layers
                        layers_dict = {}
                        for k in adata_backed.layers.keys():
                            try:
                                layers_dict[k] = adata_backed.layers[k][:]
                            except:
                                st.warning(f"Skipping layer '{k}' due to read error")

                        # Create new adata with minimal metadata first
                        adata = ad.AnnData(
                            X=X_data,
                            obs=pd.DataFrame(index=adata_backed.obs_names),
                            var=pd.DataFrame(index=adata_backed.var_names),
                            obsm=obsm_dict,
                            layers=layers_dict
                        )

                        # Copy obs columns one by one, handling errors
                        for col in adata_backed.obs.columns:
                            try:
                                col_data = adata_backed.obs[col].values
                                # Check if data is 2D
                                if hasattr(col_data, 'shape') and len(col_data.shape) > 1:
                                    if col_data.shape[1] == 1:
                                        col_data = col_data.ravel()
                                    else:
                                        st.warning(f"Skipping obs['{col}'] - unexpected shape: {col_data.shape}")
                                        continue
                                adata.obs[col] = col_data
                            except Exception as col_err:
                                st.warning(f"Skipping obs['{col}'] due to error: {str(col_err)}")

                        # Copy var columns one by one
                        for col in adata_backed.var.columns:
                            try:
                                col_data = adata_backed.var[col].values
                                if hasattr(col_data, 'shape') and len(col_data.shape) > 1:
                                    if col_data.shape[1] == 1:
                                        col_data = col_data.ravel()
                                    else:
                                        st.warning(f"Skipping var['{col}'] - unexpected shape: {col_data.shape}")
                                        continue
                                adata.var[col] = col_data
                            except Exception as col_err:
                                st.warning(f"Skipping var['{col}'] due to error: {str(col_err)}")

                        # Copy uns
                        try:
                            adata.uns = adata_backed.uns.copy()
                        except:
                            st.warning("Could not copy .uns attributes")

                        # Clean obs columns - fix any 2D arrays
                        cols_to_drop = []
                        for col in adata.obs.columns:
                            try:
                                col_data = adata.obs[col]
                                if hasattr(col_data, 'shape') and len(col_data.shape) > 1:
                                    if col_data.shape[1] == 1:
                                        # Try multiple methods to flatten
                                        try:
                                            flattened = col_data.values.ravel()
                                        except:
                                            try:
                                                flattened = np.asarray(col_data).ravel()
                                            except:
                                                flattened = [x[0] if isinstance(x, (list, np.ndarray)) and len(x) > 0 else x for x in col_data]
                                        adata.obs[col] = flattened
                                    else:
                                        st.warning(f"Removing malformed column '{col}' from metadata (shape: {col_data.shape})")
                                        cols_to_drop.append(col)
                            except Exception as col_error:
                                st.warning(f"Error processing column '{col}': {str(col_error)}. Removing column.")
                                cols_to_drop.append(col)

                        if cols_to_drop:
                            adata.obs = adata.obs.drop(columns=cols_to_drop)

                        # Clean var columns
                        cols_to_drop = []
                        for col in adata.var.columns:
                            try:
                                col_data = adata.var[col]
                                if hasattr(col_data, 'shape') and len(col_data.shape) > 1:
                                    if col_data.shape[1] == 1:
                                        # Try multiple methods to flatten
                                        try:
                                            flattened = col_data.values.ravel()
                                        except:
                                            try:
                                                flattened = np.asarray(col_data).ravel()
                                            except:
                                                flattened = [x[0] if isinstance(x, (list, np.ndarray)) and len(x) > 0 else x for x in col_data]
                                        adata.var[col] = flattened
                                    else:
                                        st.warning(f"Removing malformed column '{col}' from gene metadata (shape: {col_data.shape})")
                                        cols_to_drop.append(col)
                            except Exception as col_error:
                                st.warning(f"Error processing column '{col}': {str(col_error)}. Removing column.")
                                cols_to_drop.append(col)

                        if cols_to_drop:
                            adata.var = adata.var.drop(columns=cols_to_drop)

                        st.success("✓ Successfully cleaned and loaded h5ad file")

                    except Exception as fix_error:
                        st.error(f"""
                        ❌ **Failed to load h5ad file**

                        Error: {str(e)}

                        This h5ad file has malformed metadata (2D arrays in obs/var columns).

                        **Possible solutions:**
                        1. Re-run the CellRank analysis to generate a new h5ad file
                        2. Open the file in Python and manually clean the metadata:

                        ```python
                        import scanpy as sc
                        import anndata as ad

                        # Load the file
                        adata = sc.read_h5ad('your_file.h5ad')

                        # Check for problematic columns
                        for col in adata.obs.columns:
                            if hasattr(adata.obs[col], 'shape'):
                                print(f"{{col}}: {{adata.obs[col].shape}}")

                        # Fix 2D columns by flattening
                        for col in adata.obs.columns:
                            if hasattr(adata.obs[col], 'shape') and len(adata.obs[col].shape) > 1:
                                adata.obs[col] = adata.obs[col].values.flatten()

                        # Save cleaned file
                        adata.write_h5ad('cleaned_file.h5ad')
                        ```

                        Attempted fix error: {str(fix_error)}
                        """)
                        st.stop()
                else:
                    raise

            st.session_state.cellrank_vis_adata = adata
            st.session_state.cellrank_vis_uploaded_file = uploaded_h5ad.name

            st.info(f"✓ Loaded: {adata.n_obs} cells, {adata.n_vars} genes")

    adata = st.session_state.cellrank_vis_adata

    # Check required data
    required_data = []
    if 'terminal_states' not in adata.obs:
        required_data.append("terminal_states")
    if 'terminal_states_probs' not in adata.obsm:
        required_data.append("terminal_states_probs")

    if required_data:
        st.error(f"""
        ❌ **Missing required data: {', '.join(required_data)}**

        This file does not appear to be CellRank analysis results.
        Please upload h5ad file analyzed by CellRank analysis app.
        """)
        st.stop()

    # Get terminal states
    terminal_states = adata.obs['terminal_states'].cat.categories.tolist()
    has_initial_states = 'initial_states' in adata.obs

    # Get available embeddings
    available_bases = []
    for key in adata.obsm.keys():
        if key.startswith('X_'):
            base_name = key.replace('X_', '')
            available_bases.append(base_name)

    if not available_bases:
        st.error("❌ No embeddings found! Please ensure your h5ad file contains UMAP or other embeddings.")
        st.stop()

    # Get gene list
    gene_list = adata.var_names.tolist()

    # ========================================
    # Step 2: Configure visualization
    # ========================================
    st.header("Step 2: Configure visualization")

    with st.expander("📚 Visualization Guide", expanded=False):
        st.markdown("""
        ### Embedding Basis
        - **Multiple selection**: You can select UMAP, tSNE, PCA, etc. simultaneously
        - Individual plots are generated for each embedding
        - UMAP is selected by default (if available)

        ### Terminal States
        - Display final fate states of cell differentiation on embedding
        - Color-code which terminal state each cell belongs to
        - **Show legend**: Toggle legend display on/off

        ### Terminal States Settings (Sidebar)
        - **Discrete colormap**: State colors can be changed
        - **Change terminal state order**: Change state display order via drag & drop
        - Order changes are also reflected in color assignments

        ### Fate Probabilities
        - Display probability of each cell reaching each terminal state as heatmap
        - Probabilities range 0-1, sum of probabilities to all states equals 1
        - **Continuous colormap**: Select heatmap color scale
        - Multiple terminal states can be selected for individual visualization

        ### Initial States
        - Cell initial states (displayed only if calculated)
        - Visualize cell population as starting point of differentiation

        ### Fate Probability Heatmap
        - Display probabilities for all cells × all terminal states at once
        - **Cluster cells**: Hierarchically cluster cells by fate probability
        - Auto-sampling for 2000+ cells

        ### Gene Expression Trends
        - Gene expression changes along lineage to specific terminal state
        - Understand gene regulatory mechanisms during differentiation
        - Display expression patterns for cells sorted by fate probability
        - Display combination of smoothed curve and raw data scatter plot

        ### Download
        - **PNG format**: High-resolution bitmap (300 DPI)
        - **PDF format**: Vector format (ideal for publication and printing)
        - All generated plots can be downloaded in both formats
        """)

    # Visualization type
    viz_type = st.selectbox(
        "Visualization type",
        [
            "Terminal states",
            "Fate probabilities",
            "Initial states" if has_initial_states else None,
            "Fate probability heatmap",
            "Gene expression trends",
        ],
        help="Select visualization type"
    )

    # Sidebar for advanced options
    with st.sidebar:
        st.markdown("### Visualization Options")

        # Conditional color palette selection based on visualization type
        uses_discrete = viz_type in ["Terminal states", "Initial states"]
        uses_continuous = viz_type == "Fate probabilities"

        if uses_discrete:
            colormap_discrete = st.selectbox(
                "Colormap (discrete):",
                ["tab10", "Set1", "Set2", "Set3", "tab20", "Paired", "Dark2",
                 "tab20b", "tab20c", "Pastel1", "Pastel2", "Accent"],
                index=0,
                help="Color palette for categorical variables (Terminal/Initial states)"
            )
        else:
            colormap_discrete = "tab10"  # Default when not used

        if uses_continuous:
            colormap_continuous = st.selectbox(
                "Colormap (continuous):",
                ["viridis", "plasma", "inferno", "magma", "cividis",
                 "YlOrRd", "OrRd", "YlOrBr", "Oranges", "Reds", "Blues", "Greens", "Greys"],
                index=0,
                help="Colormap for continuous variables (fate probability)"
            )
        else:
            colormap_continuous = "viridis"  # Default when not used

        st.markdown("---")

        # Legend display toggle
        show_legend = st.checkbox(
            "Show legend",
            value=True,
            help="Whether to show legend"
        )

        st.markdown("---")
        st.markdown("### Advanced Display Options")

        # Dot size and alpha controls
        dot_size = st.slider(
            "Dot size (cell size)",
            min_value=1,
            max_value=200,
            value=10,
            step=5,
            help="Size of cell dots in scatter plot"
        )

        dot_alpha = st.slider(
            "Dot alpha (cell transparency)",
            min_value=0.1,
            max_value=1.0,
            value=0.8,
            step=0.1,
            help="Cell dot transparency (0.1=transparent, 1.0=opaque)"
        )

    st.markdown("---")

    # Common parameters
    col1, col2 = st.columns(2)

    with col1:
        # Find umap embedding if exists, otherwise use first
        default_basis = None
        for base in available_bases:
            if 'umap' in base.lower():
                default_basis = base
                break
        if default_basis is None and available_bases:
            default_basis = available_bases[0]

        basis_selections = st.multiselect(
            "Embedding basis (visualization space)",
            available_bases,
            default=[default_basis] if default_basis else [],
            help="Select embedding space for visualization. Multiple selections generate plots for each embedding"
        )

        if not basis_selections:
            st.warning("⚠️ Please select at least one embedding")
            basis_selections = [default_basis] if default_basis else []

    # Type-specific parameters
    if viz_type == "Terminal states":
        st.subheader("Terminal states settings")

        # Terminal state order management
        with st.sidebar:
            st.markdown("---")
            st.markdown("### Terminal States Settings")

            # Initialize sorted_order in session state
            if "cellrank_terminal_sorted_order" not in st.session_state:
                st.session_state.cellrank_terminal_sorted_order = terminal_states
                sorted_order = terminal_states
            else:
                sorted_order = st.session_state.get('cellrank_terminal_sorted_order')
                # Ensure sorted_order includes all current terminal states
                missing_states = [s for s in terminal_states if s not in sorted_order]
                if missing_states:
                    sorted_order = sorted_order + missing_states
                    st.session_state.cellrank_terminal_sorted_order = sorted_order

            # Color map management - always ensure all states are included
            if 'cellrank_terminal_color_map' not in st.session_state or \
               st.session_state.get('cellrank_terminal_current_cmap', '') != colormap_discrete:
                # Create color map with all current states
                st.session_state.cellrank_terminal_color_map = create_cell_color_mapping(sorted_order, colormap_discrete)
                st.session_state.cellrank_terminal_current_cmap = colormap_discrete
            else:
                # Ensure existing color map has all states
                existing_map = st.session_state.cellrank_terminal_color_map
                missing_in_map = [s for s in terminal_states if s not in existing_map]
                if missing_in_map:
                    # Add missing states to color map
                    st.session_state.cellrank_terminal_color_map = create_cell_color_mapping(sorted_order, colormap_discrete)

            # State order sorting
            sort_states = st.checkbox("Change terminal state order?")
            if sort_states:
                with st.form("terminal_state_sorter"):
                    sorted_order_new = sort_items(sorted_order.copy())
                    submitted_sort = st.form_submit_button("Done sorting")
                if submitted_sort:
                    st.session_state.cellrank_terminal_sorted_order = sorted_order_new
                    current_cmap = st.session_state.get('cellrank_terminal_current_cmap', colormap_discrete)
                    st.session_state.cellrank_terminal_color_map = create_cell_color_mapping(sorted_order_new, current_cmap)

        terminal_palette = st.session_state.get('cellrank_terminal_color_map')

    elif viz_type == "Fate probabilities":
        st.subheader("Fate probability settings")

        # Select which terminal states to show
        states_to_show = st.multiselect(
            "Terminal states to visualize",
            terminal_states,
            default=terminal_states,
            help="Select terminal states to display"
        )

        if not states_to_show:
            st.warning("⚠️ Please select at least one terminal state")

    elif viz_type == "Fate probability heatmap":
        st.subheader("Heatmap settings")

        # Clustering
        cluster_cells = st.checkbox("Cluster cells", value=True)
        cluster_states = st.checkbox("Cluster states", value=False)

        # Additional coloring
        additional_color = st.selectbox(
            "Additional annotation (optional)",
            ["None"] + [col for col in adata.obs.columns if adata.obs[col].dtype.name == 'category'],
            help="Additional annotation (clusters, etc.)"
        )

    elif viz_type == "Gene expression trends":
        st.subheader("Gene trend settings")

        st.info("""
        💡 **Tip:** For more detailed analysis, also use **Pseudotime Gene Expression** app.

        With the same h5ad file, you can:
        - Select `fate_prob_{state}` in Pseudotime selection
        - Various visualizations including heatmap and stacked area
        - Z-score normalization and cluster density analysis
        - Multi-gene overlay display
        """)

        # Select terminal state
        selected_state = st.selectbox(
            "Terminal state for lineage",
            terminal_states,
            help="Select terminal state for gene trend display"
        )

        # Gene selection
        gene_selection_method = st.radio(
            "Gene selection method",
            ["Manual selection", "Top variable genes"],
            help="Gene selection method"
        )

        if gene_selection_method == "Manual selection":
            selected_genes = st.multiselect(
                "Select genes",
                gene_list,
                max_selections=20,
                help="Select genes to display (max 20)"
            )
        else:
            n_genes = st.slider("Number of top genes", 5, 50, 10, 5)
            selected_genes = None

    # Figure size
    st.subheader("Figure settings")
    col1, col2 = st.columns(2)
    with col1:
        fig_width = st.slider("Figure width", 4, 20, 10, 1)
    with col2:
        fig_height = st.slider("Figure height", 4, 20, 8, 1)

    # ========================================
    # Step 3: Generate visualization
    # ========================================
    if st.button("🎨 Generate Visualization", type="primary"):
        st.header("Step 3: Visualization")

        with st.spinner("Generating plots..."):
            try:
                fig_files_png = []
                fig_files_pdf = []

                if viz_type == "Terminal states":
                    st.subheader("Terminal States")

                    for b in basis_selections:
                        fig, ax = plt.subplots(figsize=(fig_width, fig_height))

                        scv.pl.scatter(
                            adata,
                            basis=b,
                            color='terminal_states',
                            palette=terminal_palette if terminal_palette else None,
                            size=dot_size,
                            alpha=dot_alpha,
                            legend_loc='right margin' if show_legend else 'none',
                            ax=ax,
                            show=False,
                            title=f"Terminal States ({b})"
                        )

                        # Save as PNG
                        fig_path_png = os.path.join(cellrank_vis_temp_dir, f"terminal_states_{b}.png")
                        fig.savefig(fig_path_png, bbox_inches='tight', dpi=300)
                        fig_files_png.append(fig_path_png)

                        # Save as PDF
                        fig_path_pdf = os.path.join(cellrank_vis_temp_dir, f"terminal_states_{b}.pdf")
                        fig.savefig(fig_path_pdf, bbox_inches='tight')
                        fig_files_pdf.append(fig_path_pdf)

                        st.pyplot(fig)
                        plt.close(fig)

                    # Show state counts
                    st.write("**Cell counts per terminal state:**")
                    state_counts = adata.obs['terminal_states'].value_counts()
                    st.dataframe(state_counts)

                elif viz_type == "Fate probabilities":
                    if not states_to_show:
                        st.warning("⚠️ Please select at least one terminal state")
                    else:
                        st.subheader("Fate Probabilities")

                        # Get fate probabilities DataFrame
                        fate_probs = pd.DataFrame(
                            adata.obsm['terminal_states_probs'],
                            columns=terminal_states,
                            index=adata.obs_names
                        )

                        for state in states_to_show:
                            st.markdown(f"**Probability of reaching: {state}**")

                            # Create temporary obs column for this probability
                            adata.obs[f'fate_prob_{state}'] = fate_probs[state].values

                            for b in basis_selections:
                                fig, ax = plt.subplots(figsize=(fig_width, fig_height))

                                scv.pl.scatter(
                                    adata,
                                    basis=b,
                                    color=f'fate_prob_{state}',
                                    cmap=colormap_continuous,
                                    vmin=0,
                                    vmax=1,
                                    size=dot_size,
                                    alpha=dot_alpha,
                                    ax=ax,
                                    show=False,
                                    title=f'Fate Probability: {state} ({b})'
                                )

                                # Save as PNG
                                fig_path_png = os.path.join(cellrank_vis_temp_dir, f"fate_prob_{state}_{b}.png")
                                fig.savefig(fig_path_png, bbox_inches='tight', dpi=300)
                                fig_files_png.append(fig_path_png)

                                # Save as PDF
                                fig_path_pdf = os.path.join(cellrank_vis_temp_dir, f"fate_prob_{state}_{b}.pdf")
                                fig.savefig(fig_path_pdf, bbox_inches='tight')
                                fig_files_pdf.append(fig_path_pdf)

                                st.pyplot(fig)
                                plt.close(fig)

                            # Clean up temporary column
                            adata.obs.drop(f'fate_prob_{state}', axis=1, inplace=True)

                elif viz_type == "Initial states":
                    st.subheader("Initial States")

                    # Get initial states for color mapping
                    initial_states_list = adata.obs['initial_states'].cat.categories.tolist()
                    initial_palette_map = create_cell_color_mapping(initial_states_list, colormap_discrete)

                    for b in basis_selections:
                        fig, ax = plt.subplots(figsize=(fig_width, fig_height))

                        scv.pl.scatter(
                            adata,
                            basis=b,
                            color='initial_states',
                            palette=initial_palette_map,
                            size=dot_size,
                            alpha=dot_alpha,
                            legend_loc='right margin' if show_legend else 'none',
                            ax=ax,
                            show=False,
                            title=f"Initial States ({b})"
                        )

                        # Save as PNG
                        fig_path_png = os.path.join(cellrank_vis_temp_dir, f"initial_states_{b}.png")
                        fig.savefig(fig_path_png, bbox_inches='tight', dpi=300)
                        fig_files_png.append(fig_path_png)

                        # Save as PDF
                        fig_path_pdf = os.path.join(cellrank_vis_temp_dir, f"initial_states_{b}.pdf")
                        fig.savefig(fig_path_pdf, bbox_inches='tight')
                        fig_files_pdf.append(fig_path_pdf)

                        st.pyplot(fig)
                        plt.close(fig)

                    # Show state counts
                    st.write("**Cell counts per initial state:**")
                    state_counts = adata.obs['initial_states'].value_counts()
                    st.dataframe(state_counts)

                elif viz_type == "Fate probability heatmap":
                    st.subheader("Fate Probability Heatmap")

                    # Get fate probabilities
                    fate_probs = pd.DataFrame(
                        adata.obsm['terminal_states_probs'],
                        columns=terminal_states,
                        index=adata.obs_names
                    )

                    # Prepare data for heatmap
                    if cluster_cells:
                        # Cluster cells by fate probabilities
                        from scipy.cluster.hierarchy import linkage, dendrogram
                        from scipy.spatial.distance import pdist

                        # Compute linkage
                        linkage_matrix = linkage(fate_probs.values, method='ward')
                        dendro = dendrogram(linkage_matrix, no_plot=True)
                        cell_order = dendro['leaves']
                    else:
                        cell_order = np.arange(len(fate_probs))

                    # Sample cells if too many (for better visualization)
                    max_cells_display = 2000
                    if len(cell_order) > max_cells_display:
                        st.info(f"Sampling {max_cells_display} cells for display (total: {len(cell_order)})")
                        cell_order = np.random.choice(cell_order, max_cells_display, replace=False)

                    # Create heatmap
                    import seaborn as sns

                    fig, ax = plt.subplots(figsize=(fig_width, fig_height))

                    plot_data = fate_probs.iloc[cell_order]

                    sns.heatmap(
                        plot_data.T,
                        cmap='viridis',
                        vmin=0,
                        vmax=1,
                        cbar_kws={'label': 'Fate Probability'},
                        xticklabels=False,
                        yticklabels=True,
                        ax=ax
                    )

                    ax.set_xlabel("Cells")
                    ax.set_ylabel("Terminal States")
                    ax.set_title("Fate Probability Heatmap")

                    # Save as PNG
                    fig_path_png = os.path.join(cellrank_vis_temp_dir, "fate_prob_heatmap.png")
                    fig.savefig(fig_path_png, bbox_inches='tight', dpi=300)
                    fig_files_png.append(fig_path_png)

                    # Save as PDF
                    fig_path_pdf = os.path.join(cellrank_vis_temp_dir, "fate_prob_heatmap.pdf")
                    fig.savefig(fig_path_pdf, bbox_inches='tight')
                    fig_files_pdf.append(fig_path_pdf)

                    st.pyplot(fig)
                    plt.close(fig)

                elif viz_type == "Gene expression trends":
                    st.subheader(f"Gene Trends toward {selected_state}")

                    # Get genes to plot
                    if gene_selection_method == "Manual selection":
                        if not selected_genes:
                            st.warning("⚠️ Please select at least one gene")
                            st.stop()
                        genes_to_plot = [g for g in selected_genes if g in adata.var_names]
                    else:
                        # Get top variable genes
                        if 'highly_variable' in adata.var.columns:
                            var_genes = adata.var_names[adata.var['highly_variable']].tolist()
                        else:
                            # Use genes with highest variance
                            gene_var = np.var(adata.X.toarray() if hasattr(adata.X, 'toarray') else adata.X, axis=0)
                            top_indices = np.argsort(gene_var)[-n_genes:]
                            var_genes = adata.var_names[top_indices].tolist()

                        genes_to_plot = var_genes[:n_genes]

                    st.write(f"**Plotting {len(genes_to_plot)} genes:**")
                    st.write(", ".join(genes_to_plot))

                    # Get fate probabilities for selected state
                    fate_probs = pd.DataFrame(
                        adata.obsm['terminal_states_probs'],
                        columns=terminal_states,
                        index=adata.obs_names
                    )
                    state_prob = fate_probs[selected_state].values

                    # Sort cells by probability
                    sorted_indices = np.argsort(state_prob)

                    # Get expression data
                    if hasattr(adata.X, 'toarray'):
                        expr_data = adata.X.toarray()
                    else:
                        expr_data = adata.X

                    # Create trend plots
                    n_rows = int(np.ceil(len(genes_to_plot) / 3))
                    n_cols = 3
                    fig, axes_raw = plt.subplots(n_rows, n_cols, figsize=(fig_width, fig_height))

                    # Convert axes to 1D array consistently
                    if n_rows == 1 and n_cols == 1:
                        # Single subplot
                        axes = [axes_raw]
                    elif n_rows == 1:
                        # Single row, multiple columns
                        axes = list(axes_raw)
                    else:
                        # Multiple rows
                        axes = list(axes_raw.flatten())

                    for idx, gene in enumerate(genes_to_plot):
                        if idx >= len(axes):
                            break

                        ax = axes[idx]
                        gene_idx = adata.var_names.get_loc(gene)
                        gene_expr = expr_data[:, gene_idx][sorted_indices]

                        # Smooth expression with rolling average
                        window_size = max(20, len(gene_expr) // 50)
                        gene_expr_smooth = pd.Series(gene_expr).rolling(window=window_size, center=True).mean()

                        ax.plot(state_prob[sorted_indices], gene_expr_smooth, linewidth=2)
                        ax.scatter(state_prob[sorted_indices], gene_expr, alpha=0.1, s=max(1, dot_size//10))
                        ax.set_xlabel(f'Probability → {selected_state}')
                        ax.set_ylabel('Expression')
                        ax.set_title(gene)
                        ax.grid(True, alpha=0.3)

                    # Remove empty subplots
                    for idx in range(len(genes_to_plot), len(axes)):
                        fig.delaxes(axes[idx])

                    plt.tight_layout()

                    # Save as PNG
                    fig_path_png = os.path.join(cellrank_vis_temp_dir, f"gene_trends_{selected_state}.png")
                    fig.savefig(fig_path_png, bbox_inches='tight', dpi=300)
                    fig_files_png.append(fig_path_png)

                    # Save as PDF
                    fig_path_pdf = os.path.join(cellrank_vis_temp_dir, f"gene_trends_{selected_state}.pdf")
                    fig.savefig(fig_path_pdf, bbox_inches='tight')
                    fig_files_pdf.append(fig_path_pdf)

                    st.pyplot(fig)
                    plt.close(fig)

                # Download section
                if fig_files_png:
                    st.success(f"✅ Generated {len(fig_files_png)} plot(s)")

                    st.subheader("Download plots")

                    # Create two columns for PNG and PDF downloads
                    col_png, col_pdf = st.columns(2)

                    with col_png:
                        st.markdown("**PNG Format**")
                        for fig_file in fig_files_png:
                            file_name = os.path.basename(fig_file)
                            with open(fig_file, "rb") as f:
                                st.download_button(
                                    label=f"⬇️ {file_name}",
                                    data=f.read(),
                                    file_name=file_name,
                                    mime="image/png",
                                    key=f"png_{file_name}"
                                )

                    with col_pdf:
                        st.markdown("**PDF Format**")
                        for fig_file in fig_files_pdf:
                            file_name = os.path.basename(fig_file)
                            with open(fig_file, "rb") as f:
                                st.download_button(
                                    label=f"⬇️ {file_name}",
                                    data=f.read(),
                                    file_name=file_name,
                                    mime="application/pdf",
                                    key=f"pdf_{file_name}"
                                )

            except Exception as e:
                st.error(f"❌ Error during visualization: {str(e)}")
                st.exception(e)

else:
    st.info("👆 Upload h5ad file from CellRank analysis to start")
