"""
TFvelo to Dynamo Converter
Converts TFvelo velocity results to Dynamo-compatible format for perturbation analysis
"""

import streamlit as st
import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time
import tempfile
import hashlib
from scipy.sparse import issparse

# Import dynamo
try:
    import dynamo as dyn
    DYNAMO_AVAILABLE = True
except ImportError:
    DYNAMO_AVAILABLE = False

# Import TFvelo
import sys
tfvelo_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'TFvelo')
if tfvelo_path not in sys.path:
    sys.path.insert(0, tfvelo_path)
try:
    import TFvelo as TFv
    TFVELO_AVAILABLE = True
except ImportError:
    TFVELO_AVAILABLE = False

st.set_page_config(page_title="TFvelo to Dynamo", page_icon="🔄", layout="wide")

st.title("🔄 TFvelo to Dynamo Converter")

st.markdown("""
Converts TFvelo velocity estimation results into Dynamo's Vector Field format,
enabling **In Silico Perturbation analysis**.

### Processing Flow
```
TFvelo velocity → PCA projection → Vector Field construction → Jacobian calculation ready
```
""")

if not DYNAMO_AVAILABLE:
    st.error("""
    ❌ **Dynamo is not installed**

    Please install Dynamo using:
    ```bash
    pip install dynamo-release
    ```
    """)
    st.stop()


def get_file_hash(file_obj):
    """Get MD5 hash of file content for cache key"""
    content = file_obj.getvalue()
    return hashlib.md5(content).hexdigest()


@st.cache_resource
def load_h5ad_file(_file_obj, _file_hash):
    """Load h5ad file with caching"""
    with tempfile.NamedTemporaryFile(delete=False, suffix=".h5ad") as tmp:
        tmp.write(_file_obj.getvalue())
        tmp_path = tmp.name

    adata = sc.read_h5ad(tmp_path)
    os.unlink(tmp_path)

    return adata


# Initialize session state
if "tfvelo_dynamo_temp_dir" not in st.session_state:
    temp_dir = os.path.join("temp", f"tfvelo_dynamo_{round(time.time())}")
    os.makedirs(temp_dir, exist_ok=True)
    st.session_state.tfvelo_dynamo_temp_dir = temp_dir


# ========================================
# Step 1: Upload TFvelo result
# ========================================
st.header("Step 1: Upload TFvelo Result")

st.markdown("""
**Required data:**
- ✅ Velocity computed by TFvelo (`adata.layers['velocity']`)
- ✅ Embedding (UMAP, PCA, etc.)
- ✅ Gene expression data
""")

uploaded_file = st.file_uploader(
    "Upload TFvelo result (h5ad)",
    type=['h5ad'],
    key="tfvelo_upload",
    help="h5ad file generated by the TFvelo app"
)

if uploaded_file is not None:
    # Load file
    file_hash = get_file_hash(uploaded_file)

    with st.spinner("Loading TFvelo result..."):
        adata = load_h5ad_file(uploaded_file, file_hash)
        st.success(f"✅ Loaded: {adata.n_obs} cells, {adata.n_vars} genes")

    # ========================================
    # Step 2: Validate TFvelo data
    # ========================================
    st.header("Step 2: Data Validation")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Velocity Layers")

        # Check for velocity layers
        velocity_layers = []
        for layer in adata.layers.keys():
            if 'velo' in layer.lower() or 'velocity' in layer.lower():
                velocity_layers.append(layer)

        if velocity_layers:
            st.success(f"✅ Velocity layers found: {len(velocity_layers)}")
            for layer in velocity_layers:
                shape = adata.layers[layer].shape
                st.write(f"  - `{layer}`: {shape}")
        else:
            st.error("❌ No velocity layers found")
            st.info("TFvelo results require a `velocity` or `velo_hat` layer")

        # Other useful layers
        st.subheader("Other Layers")
        other_layers = [l for l in adata.layers.keys() if l not in velocity_layers]
        if other_layers:
            for layer in other_layers[:10]:  # Show first 10
                st.write(f"  - `{layer}`")
            if len(other_layers) > 10:
                st.write(f"  ... and {len(other_layers) - 10} more")

    with col2:
        st.subheader("Embeddings")

        # Check for embeddings
        embedding_keys = [k for k in adata.obsm.keys() if k.startswith('X_')]
        if embedding_keys:
            st.success(f"✅ Embeddings found: {len(embedding_keys)}")
            for key in embedding_keys:
                shape = adata.obsm[key].shape
                st.write(f"  - `{key}`: {shape}")
        else:
            st.error("❌ No embeddings found")

        # Check for PCA specifically (needed for vector field)
        if 'X_pca' in adata.obsm:
            st.success("✅ PCA available (recommended for Vector Field)")
        else:
            st.warning("⚠️ PCA not found - will compute if needed")

        # Check existing Dynamo data
        st.subheader("Existing Dynamo Data")
        vecfld_keys = [k for k in adata.uns.keys() if k.startswith('VecFld')]
        if vecfld_keys:
            st.info(f"Vector fields already exist: {vecfld_keys}")
        else:
            st.write("No existing Vector Field")

    # ========================================
    # Step 3: Configuration
    # ========================================
    if velocity_layers and embedding_keys:
        st.header("Step 3: Conversion Settings")

        # Get TFvelo gene count for PCA recalculation option
        n_total_genes = adata.n_vars
        n_obs = adata.n_obs

        # Count genes with valid velocity using min_loss column (TFvelo stores this)
        # min_loss < 1000000 indicates genes where TFvelo successfully computed velocity
        if 'min_loss' in adata.var.columns:
            vel_genes_mask = adata.var['min_loss'] < 1000000
            n_vel_genes = vel_genes_mask.sum()
        else:
            # Fallback: count from velocity layer
            vel_check = adata.layers.get('velocity', None)
            if vel_check is not None:
                if issparse(vel_check):
                    vel_check = vel_check.toarray()
                n_vel_genes = (np.abs(vel_check).sum(axis=0) > 0).sum()
            else:
                n_vel_genes = n_total_genes

        # PCA recalculation option
        st.subheader("PCA Settings")

        use_tfvelo_pca = st.checkbox(
            f"Recalculate PCA using velocity genes only ({n_vel_genes}/{n_total_genes} genes)",
            value=True,
            help=f"""Recalculate PCA using only genes with non-zero velocity.

**Current data:**
- Total genes: {n_total_genes}
- Non-zero velocity: {n_vel_genes}

**Background:**
- TFvelo computes velocity only for velocity genes
- With original PCA (all HVG genes), velocity projection becomes small
- This causes very small values in Jacobian calculation

**When this option is enabled:**
- Filter adata to velocity genes only
- Compute PCA from filtered genes
- Vector Field is built in the new PCA space
- Jacobian values are at an appropriate scale

**Note:** UMAP remains unchanged (for visualization)"""
        )

        if use_tfvelo_pca:
            # Calculate max PCA components (based on velocity genes)
            max_pca_comps = min(50, n_vel_genes - 1, n_obs - 1)
            default_pca_comps = min(30, max_pca_comps)

            n_pca_comps = st.slider(
                "PCA components",
                min_value=2,
                max_value=max_pca_comps,
                value=default_pca_comps,
                help=f"Number of PCA dimensions for TFvelo genes (max: {max_pca_comps})"
            )

            st.info(f"""
            📊 **New PCA settings:**
            - Velocity gene count: {n_vel_genes} (after filtering)
            - PCA dimensions: {n_pca_comps}
            - Stored in: `X_pca_tfvelo`
            - Vector Field basis: `pca_tfvelo` (automatic)
            """)

        st.divider()

        col1, col2 = st.columns(2)

        with col1:
            # Select velocity layer to use
            # Default to 'velocity' if available
            default_vel_idx = 0
            if 'velocity' in velocity_layers:
                default_vel_idx = velocity_layers.index('velocity')

            velocity_layer = st.selectbox(
                "Velocity layer to use",
                options=velocity_layers,
                index=default_vel_idx,
                help="""Select the TFvelo velocity layer

**Layer descriptions:**
- `velocity` (recommended): TFvelo main velocity estimate
- `velo_hat`: Fitted predicted velocity
- `velo_t`: Time derivative velocity
- `velo_normed`: Normalized to [0,1] (for visualization, not suitable for Vector Field)"""
            )

            # Select basis for vector field
            available_bases = [k.replace('X_', '') for k in embedding_keys]

            # When use_tfvelo_pca is checked, auto-set to pca_tfvelo
            if use_tfvelo_pca:
                vf_basis = 'pca_tfvelo'  # Will be created during conversion
                st.text_input(
                    "Basis for Vector Field",
                    value="pca_tfvelo (auto)",
                    disabled=True,
                    help="Uses PCA of TFvelo genes (auto-configured)"
                )
            else:
                # Prefer PCA for vector field
                default_basis_idx = 0
                if 'pca' in available_bases:
                    default_basis_idx = available_bases.index('pca')

                vf_basis = st.selectbox(
                    "Basis for Vector Field",
                    options=available_bases,
                    index=default_basis_idx,
                    help="Space used for Vector Field construction. PCA recommended."
                )

            # Visualization basis - allow all reductions, prefer ones with 'umap'
            # Find default: prioritize bases containing 'umap' (case-insensitive)
            umap_bases = [b for b in available_bases if 'umap' in b.lower()]
            if umap_bases:
                default_viz_idx = available_bases.index(umap_bases[0])
            else:
                default_viz_idx = 0

            viz_basis = st.selectbox(
                "Basis for Visualization",
                options=available_bases,
                index=default_viz_idx,
                help="Space used for visualization (UMAP, tSNE, etc.)"
            )

        with col2:
            # Vector field parameters
            st.subheader("Vector Field Parameters")

            M = st.slider(
                "Number of basis functions (M)",
                min_value=50, max_value=500, value=100,
                help="""Number of basis functions for SparseVFC (Sparse Vector Field Consensus).

**What is M:** Number of Radial Basis Functions used to approximate the vector field.

**Guidelines:**
- 100 (default): Sufficient for most cases
- 300-500: For complex branching or multiple attractors
- Setting above the number of cells has no effect

**Note:** Too large may risk overfitting"""
            )

            st.info("💡 Jacobian is automatically computed during perturbation analysis")

        # ========================================
        # Step 4: Run Conversion
        # ========================================
        st.header("Step 4: Run Conversion")

        if st.button("🚀 Convert to Dynamo Format", type="primary"):
            progress_bar = st.progress(0)
            status_text = st.empty()

            try:
                # Make a copy to avoid modifying cached data
                adata_dynamo = adata.copy()

                # Fix categorical/string boolean columns in var and ensure use_for_pca exists
                for col in ['highly_variable', 'use_for_pca']:
                    if col in adata_dynamo.var.columns:
                        col_data = adata_dynamo.var[col]
                        if col_data.dtype == 'category' or col_data.dtype == object:
                            # Convert string 'True'/'False' to boolean
                            adata_dynamo.var[col] = col_data.astype(str).str.lower() == 'true'
                            st.info(f"Converted `{col}` column to boolean")

                # Ensure dynamo required columns exist
                # Reference: dynamo tutorial - these columns are created by:
                # - use_for_pca: dyn.pp.pca() or recipe_monocle() - genes used for PCA
                # - use_for_dynamics: dyn.tl.dynamics() - genes with valid velocity
                # - use_for_transition: dyn.tl.cell_velocities() - genes used for transition matrix

                def get_hvg_mask(adata):
                    """Get HVG boolean mask from available columns"""
                    if 'highly_variable' in adata.var.columns:
                        hv = adata.var['highly_variable']
                        if hv.dtype == 'category' or hv.dtype == object:
                            return hv.astype(str).str.lower() == 'true'
                        else:
                            return hv.astype(bool)
                    return None

                hvg_mask = get_hvg_mask(adata_dynamo)
                created_cols = []

                for col_name in ['use_for_pca', 'use_for_dynamics', 'use_for_transition']:
                    if col_name not in adata_dynamo.var.columns:
                        if hvg_mask is not None:
                            adata_dynamo.var[col_name] = hvg_mask
                        else:
                            adata_dynamo.var[col_name] = True
                        created_cols.append(col_name)
                    else:
                        # Ensure boolean type
                        col = adata_dynamo.var[col_name]
                        if col.dtype == 'category' or col.dtype == object:
                            adata_dynamo.var[col_name] = col.astype(str).str.lower() == 'true'
                            created_cols.append(f"{col_name}(converted)")

                if created_cols:
                    st.info(f"Created dynamo columns: {', '.join(created_cols)}")

                # Add dynamo metadata (uns['dynamics'] and uns['pp'])
                # These are normally created by dyn.pp.recipe_monocle() and dyn.tl.dynamics()
                if 'pp' not in adata_dynamo.uns:
                    adata_dynamo.uns['pp'] = {
                        'experiment_type': 'conventional',  # spliced/unspliced based velocity
                        'has_splicing': True,
                        'has_labeling': False,
                        'splicing_labeling': False,
                        'has_protein': False,
                        'tkey': None,
                        'X_norm_method': 'log1p',  # Assume log-normalized data
                        'layers_norm_method': None,
                    }
                    st.info("Created `uns['pp']` metadata for dynamo")
                else:
                    # Ensure all required keys exist
                    pp_keys = {
                        'X_norm_method': 'log1p',
                        'experiment_type': 'conventional',
                        'has_splicing': True,
                    }
                    for key, value in pp_keys.items():
                        if key not in adata_dynamo.uns['pp']:
                            adata_dynamo.uns['pp'][key] = value

                if 'dynamics' not in adata_dynamo.uns:
                    adata_dynamo.uns['dynamics'] = {
                        'experiment_type': 'conventional',
                        'has_splicing': True,
                        'has_labeling': False,
                        'splicing_labeling': False,
                        'has_protein': False,
                        'est_method': 'ols',  # TFvelo uses different method but ols is default
                        'model': 'deterministic',
                        'use_smoothed': True,  # We create M_s layer below
                        'NTR_vel': False,
                        'log_unnormalized': False,
                    }
                    st.info("Created `uns['dynamics']` metadata for dynamo")
                else:
                    # Ensure all required keys exist
                    dynamics_keys = {
                        'use_smoothed': True,
                        'NTR_vel': False,
                        'log_unnormalized': False,
                        'experiment_type': 'conventional',
                    }
                    for key, value in dynamics_keys.items():
                        if key not in adata_dynamo.uns['dynamics']:
                            adata_dynamo.uns['dynamics'][key] = value

                # Step 1: Prepare velocity
                status_text.text("Step 1/4: Preparing velocity data...")
                progress_bar.progress(10)

                # Ensure velocity is in the expected format
                velocity_data = adata_dynamo.layers[velocity_layer]
                if issparse(velocity_data):
                    velocity_data = velocity_data.toarray()

                # Store as 'velocity' if not already
                if velocity_layer != 'velocity':
                    adata_dynamo.layers['velocity'] = velocity_data
                    st.info(f"Copied `{velocity_layer}` to `velocity` layer")

                # Also create velocity_S (dynamo's expected spliced velocity layer name)
                if 'velocity_S' not in adata_dynamo.layers:
                    adata_dynamo.layers['velocity_S'] = velocity_data.copy()
                    st.info("Created `velocity_S` layer for dynamo compatibility")

                # Step 2: Compute PCA
                status_text.text("Step 2/4: Computing/Configuring PCA...")
                progress_bar.progress(20)

                if use_tfvelo_pca:
                    # Filter to genes with valid velocity using min_loss column
                    if 'min_loss' in adata_dynamo.var.columns:
                        vel_genes_mask = (adata_dynamo.var['min_loss'] < 1000000).values
                        n_vel_genes = vel_genes_mask.sum()
                        st.info(f"Filtering to velocity genes: {n_vel_genes}/{adata_dynamo.n_vars} genes (min_loss < 1000000)")
                    else:
                        # Fallback: use velocity layer
                        vel = adata_dynamo.layers[velocity_layer]
                        if issparse(vel):
                            vel = vel.toarray()
                        vel_sum = np.abs(vel).sum(axis=0)
                        vel_genes_mask = vel_sum > 0
                        n_vel_genes = vel_genes_mask.sum()
                        st.info(f"Filtering to velocity genes: {n_vel_genes}/{adata_dynamo.n_vars} genes (velocity non-zero)")

                    # Filter adata to velocity genes only
                    adata_dynamo = adata_dynamo[:, vel_genes_mask].copy()

                    # Update velocity data after filtering
                    velocity_data = adata_dynamo.layers[velocity_layer]
                    if issparse(velocity_data):
                        velocity_data = velocity_data.toarray()
                    adata_dynamo.layers['velocity'] = velocity_data
                    if 'velocity_S' in adata_dynamo.layers:
                        adata_dynamo.layers['velocity_S'] = velocity_data.copy()

                    # Recalculate n_pca_comps based on filtered gene count
                    n_filtered_genes = adata_dynamo.n_vars
                    n_pca_comps = min(n_pca_comps, n_filtered_genes - 1, adata_dynamo.n_obs - 1)

                    st.info(f"Computing PCA using {n_filtered_genes} velocity genes, {n_pca_comps} components...")

                    # Get expression data
                    X = adata_dynamo.X.toarray() if issparse(adata_dynamo.X) else adata_dynamo.X.copy()

                    # Calculate and store mean for centering (needed for perturbation analysis)
                    X_mean = X.mean(axis=0)
                    X_centered = X - X_mean

                    # Compute PCA using sklearn for more control
                    from sklearn.decomposition import PCA
                    pca_model = PCA(n_components=n_pca_comps, svd_solver='arpack')
                    X_pca_tfvelo = pca_model.fit_transform(X_centered)

                    # Store PCA coordinates
                    adata_dynamo.obsm['X_pca_tfvelo'] = X_pca_tfvelo

                    # Store PCA loadings (components_.T gives (n_genes, n_components))
                    pca_loadings = pca_model.components_.T  # shape: (n_genes, n_components)
                    adata_dynamo.uns['PCs_pca_tfvelo'] = pca_loadings
                    adata_dynamo.uns['PCs'] = pca_loadings  # Dynamo expects 'PCs' in uns

                    # Store gene names and mean vector (needed for perturbation analysis)
                    adata_dynamo.uns['pca_tfvelo_genes'] = list(adata_dynamo.var_names)
                    adata_dynamo.uns['pca_tfvelo_mean'] = X_mean

                    # Also store variance explained for reference
                    adata_dynamo.uns['pca_tfvelo_variance_ratio'] = pca_model.explained_variance_ratio_

                    # Remove any existing varm PCs entries (dynamo checks varm first)
                    pcs_varm_keys = [k for k in adata_dynamo.varm.keys() if k.startswith('PCs_')]
                    for k in pcs_varm_keys:
                        del adata_dynamo.varm[k]

                    total_var = pca_model.explained_variance_ratio_.sum() * 100
                    st.success(f"✅ Filtered to {n_filtered_genes} velocity genes")
                    st.success(f"✅ Created `X_pca_tfvelo` ({n_pca_comps} components, {total_var:.1f}% variance explained)")
                    st.info(f"Stored PCA loadings in `uns['PCs_pca_tfvelo']` and `uns['PCs']`")
                    st.info(f"Stored gene names ({n_filtered_genes}) in `uns['pca_tfvelo_genes']`")
                    if pcs_varm_keys:
                        st.info(f"Removed {len(pcs_varm_keys)} PCs entries from varm")

                else:
                    # Use existing PCA logic
                    if 'X_pca' not in adata_dynamo.obsm:
                        st.info("Computing PCA...")
                        sc.tl.pca(adata_dynamo, n_comps=50)

                    # Copy TFvelo's PCA loadings to dynamo's expected key
                    # TFvelo stores PCA loadings as 'PCs_{basis}' but dynamo expects 'PCs'
                    # Use the PCs corresponding to the selected vf_basis
                    # NOTE: dynamo.pd.perturbation checks uns['PCs'], while jacobian checks both uns and varm
                    basis_pcs_key = f'PCs_{vf_basis}'
                    pca_keys = [k for k in adata_dynamo.varm.keys() if k.startswith('PCs_')]

                    pcs_to_copy = None
                    pcs_source_key = None

                    if basis_pcs_key in adata_dynamo.varm:
                        pcs_to_copy = adata_dynamo.varm[basis_pcs_key].copy()
                        pcs_source_key = basis_pcs_key
                    elif pca_keys:
                        pcs_to_copy = adata_dynamo.varm[pca_keys[0]].copy()
                        pcs_source_key = pca_keys[0]
                        st.warning(f"PCs for '{vf_basis}' not found, using `{pcs_source_key}` instead")

                    if pcs_to_copy is not None:
                        # Copy to both uns keys for full dynamo compatibility:
                        # - uns['PCs_{vf_basis}'] (e.g., 'PCs_rna.pca') for perturbation()
                        # - uns['PCs'] for jacobian() which uses default Qkey='PCs'
                        target_key = f'PCs_{vf_basis}'
                        adata_dynamo.uns[target_key] = pcs_to_copy
                        adata_dynamo.uns['PCs'] = pcs_to_copy

                        # Remove varm PCs entries so that dynamo_perturbation will use uns instead
                        # (dynamo_perturbation checks varm first, which causes issues with jacobian)
                        pcs_varm_keys = [k for k in adata_dynamo.varm.keys() if k.startswith('PCs_')]
                        for k in pcs_varm_keys:
                            del adata_dynamo.varm[k]

                        st.info(f"Copied `{pcs_source_key}` to `uns['{target_key}']` and `uns['PCs']` for dynamo compatibility")
                        st.info(f"Removed {len(pcs_varm_keys)} PCs entries from varm (dynamo will use uns)")

                # Step 3: Project velocities to embedding using TFvelo's method
                status_text.text("Step 3/4: Projecting velocities to embedding space...")
                progress_bar.progress(40)

                # Ensure we have the expression matrix for xkey
                # TFvelo uses M_total by default, fallback to M_s or spliced
                if 'M_total' not in adata_dynamo.layers:
                    if 'M_s' in adata_dynamo.layers:
                        adata_dynamo.layers['M_total'] = adata_dynamo.layers['M_s'].copy()
                    elif 'spliced' in adata_dynamo.layers:
                        adata_dynamo.layers['M_total'] = adata_dynamo.layers['spliced'].copy()
                    else:
                        # Use normalized expression
                        adata_dynamo.layers['M_total'] = adata_dynamo.X.toarray() if issparse(adata_dynamo.X) else adata_dynamo.X.copy()

                # Also create M_s for compatibility
                if 'M_s' not in adata_dynamo.layers:
                    adata_dynamo.layers['M_s'] = adata_dynamo.layers['M_total'].copy()

                # Create X_spliced and X_unspliced for dynamo compatibility
                # dynamo's cell_velocities() requires these layers
                if 'X_spliced' not in adata_dynamo.layers:
                    adata_dynamo.layers['X_spliced'] = adata_dynamo.layers['M_total'].copy()
                if 'X_unspliced' not in adata_dynamo.layers:
                    # Create dummy unspliced layer (required by dynamo but not used for TFvelo)
                    adata_dynamo.layers['X_unspliced'] = np.zeros_like(adata_dynamo.layers['M_total'])

                # Use transition matrix-based velocity projection
                # This is the correct method used by TFvelo/scvelo (not direct V @ PCs)
                # Formula: ν̃_i = Σ_j (π_ij - 1/n) · δ̃_ij
                st.info("Using transition matrix-based velocity projection...")

                try:
                    from sklearn.neighbors import NearestNeighbors
                    from scipy.sparse import csr_matrix

                    # Get velocity and expression data
                    vel = adata_dynamo.layers['velocity']
                    if issparse(vel):
                        vel = vel.toarray()

                    X_expr = adata_dynamo.layers['M_total']
                    if issparse(X_expr):
                        X_expr = X_expr.toarray()

                    X_emb = adata_dynamo.obsm[f'X_{vf_basis}']
                    n_cells = X_emb.shape[0]
                    n_dims = X_emb.shape[1]

                    # Step 3a: Build velocity graph using cosine similarity
                    # Compute neighbors in expression space
                    n_neighbors = min(30, n_cells - 1)
                    nn = NearestNeighbors(n_neighbors=n_neighbors + 1, metric='euclidean')
                    nn.fit(X_expr)
                    distances, indices = nn.kneighbors(X_expr)

                    # Remove self-connections
                    indices = indices[:, 1:]  # shape: (n_cells, n_neighbors)

                    # Compute cosine similarity between velocity and cell state transitions
                    # π_ij = cos(velocity_i, x_j - x_i)
                    rows, cols, vals = [], [], []
                    for i in range(n_cells):
                        neighs = indices[i]
                        dX = X_expr[neighs] - X_expr[i]  # (n_neighbors, n_genes)

                        # Compute cosine similarity
                        v_i = vel[i]
                        v_norm = np.linalg.norm(v_i)
                        if v_norm > 0:
                            for j_idx, j in enumerate(neighs):
                                dX_j = dX[j_idx]
                                dX_norm = np.linalg.norm(dX_j)
                                if dX_norm > 0:
                                    cos_sim = np.dot(v_i, dX_j) / (v_norm * dX_norm)
                                    rows.append(i)
                                    cols.append(j)
                                    vals.append(cos_sim)

                    # Build velocity graph (cosine similarities)
                    T = csr_matrix((vals, (rows, cols)), shape=(n_cells, n_cells))
                    T_data = T.toarray()

                    # Store velocity graph (before softmax)
                    T_pos = np.clip(T_data, 0, None)
                    T_neg = np.clip(T_data, None, 0)

                    # Apply softmax normalization (Gaussian kernel) as in TFvelo/scvelo
                    # π̃_ij = exp(π_ij / σ) / Σ_k exp(π_ik / σ)
                    # where σ = scale (default 10)
                    sigma = 10.0  # TFvelo default scale parameter

                    # Apply softmax to positive cosine similarities only
                    T_exp = np.exp(T_pos / sigma)
                    # Zero out where original was zero (non-neighbors)
                    T_exp[T_pos == 0] = 0

                    # Row normalize (softmax)
                    row_sums = T_exp.sum(axis=1, keepdims=True)
                    row_sums[row_sums == 0] = 1
                    T_norm = T_exp / row_sums

                    # Step 3b: Project to embedding space
                    # V_emb[i] = Σ_j (T[i,j] - mean) * (x_j - x_i) / ||x_j - x_i||
                    V_emb = np.zeros((n_cells, n_dims))

                    for i in range(n_cells):
                        # Get non-zero neighbors
                        neighs = np.where(T_norm[i] > 0)[0]
                        if len(neighs) == 0:
                            continue

                        probs = T_norm[i, neighs]
                        dX_emb = X_emb[neighs] - X_emb[i]  # (n_neighs, n_dims)

                        # Normalize directions
                        norms = np.linalg.norm(dX_emb, axis=1, keepdims=True)
                        norms[norms == 0] = 1
                        dX_emb_norm = dX_emb / norms

                        # Weighted average
                        V_emb[i] = np.sum((probs - probs.mean())[:, None] * dX_emb_norm, axis=0)

                    # Autoscale for visualization
                    scale = np.percentile(np.linalg.norm(V_emb, axis=1), 95)
                    if scale > 0:
                        V_emb = V_emb / scale * 0.5  # Scale to reasonable magnitude

                    # Store result
                    adata_dynamo.obsm[f'velocity_{vf_basis}'] = V_emb

                    # Also store the velocity graph for compatibility
                    adata_dynamo.uns['velocity_graph'] = csr_matrix(T_pos)
                    adata_dynamo.uns['velocity_graph_neg'] = csr_matrix(T_neg)

                    st.success("✅ Velocity projected using transition matrix method")
                    st.info(f"Velocity embedding shape: {V_emb.shape}, norm range: [{np.linalg.norm(V_emb, axis=1).min():.4f}, {np.linalg.norm(V_emb, axis=1).max():.4f}]")

                except Exception as e:
                    st.error(f"Transition matrix projection failed: {e}")
                    import traceback
                    st.code(traceback.format_exc())
                    raise

                # Step 4: Build Vector Field
                status_text.text("Step 4/4: Building Vector Field (this may take a while)...")
                progress_bar.progress(60)

                # Clean velocity data to prevent "probabilities do not sum to 1" error
                vel_key = f'velocity_{vf_basis}'
                if vel_key in adata_dynamo.obsm:
                    vel_data = adata_dynamo.obsm[vel_key].copy()
                    # Replace NaN/inf with 0
                    vel_data = np.nan_to_num(vel_data, nan=0.0, posinf=0.0, neginf=0.0)
                    # Add small noise to zero-velocity cells to avoid sampling issues
                    zero_rows = np.all(vel_data == 0, axis=1)
                    if np.any(zero_rows):
                        vel_data[zero_rows] = np.random.randn(np.sum(zero_rows), vel_data.shape[1]) * 1e-6
                    adata_dynamo.obsm[vel_key] = vel_data

                try:
                    dyn.vf.VectorField(
                        adata_dynamo,
                        basis=vf_basis,
                        M=M
                    )
                    st.success(f"✅ Vector Field constructed on `{vf_basis}` basis")
                except ValueError as e:
                    if "probabilities" in str(e):
                        st.warning(f"⚠️ Vector Field construction failed: {e}")
                        st.info("Trying with smaller sample size...")
                        # Try with smaller M
                        dyn.vf.VectorField(
                            adata_dynamo,
                            basis=vf_basis,
                            M=min(M // 2, 100)
                        )
                        st.success(f"✅ Vector Field constructed with reduced sample size")
                    else:
                        raise

                progress_bar.progress(100)
                status_text.text("Conversion complete!")

                # ========================================
                # Results and Download
                # ========================================
                st.header("Results")

                # Debug: Show metadata state after conversion
                with st.expander("🔍 Debug: Metadata state"):
                    st.write("**uns['pp']:**")
                    if 'pp' in adata_dynamo.uns:
                        st.json(adata_dynamo.uns['pp'])
                    else:
                        st.error("uns['pp'] not found!")

                    st.write("**uns['dynamics']:**")
                    if 'dynamics' in adata_dynamo.uns:
                        st.json(adata_dynamo.uns['dynamics'])
                    else:
                        st.error("uns['dynamics'] not found!")

                    st.write("**All uns keys:**")
                    st.write(list(adata_dynamo.uns.keys()))

                # Show what was added
                st.subheader("Added Data")

                col1, col2 = st.columns(2)

                with col1:
                    st.write("**New .uns keys:**")
                    new_uns = [k for k in adata_dynamo.uns.keys() if k.startswith('VecFld')]
                    for key in new_uns:
                        st.write(f"  - `{key}`")

                with col2:
                    st.write("**New .obsm keys:**")
                    new_obsm = [k for k in adata_dynamo.obsm.keys() if 'velocity' in k.lower()]
                    for key in new_obsm:
                        st.write(f"  - `{key}`")

                # Visualization
                st.subheader("Velocity Stream Visualization")

                try:
                    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

                    # Get color column
                    color_col = adata_dynamo.obs.columns[0] if len(adata_dynamo.obs.columns) > 0 else None

                    # Original embedding
                    sc.pl.embedding(
                        adata_dynamo,
                        basis=viz_basis,
                        color=color_col,
                        ax=axes[0],
                        show=False,
                        title=f"Original ({viz_basis.upper()})"
                    )

                    # Velocity embedding - use scvelo if available, otherwise show arrows manually
                    try:
                        import scvelo as scv
                        # scvelo's velocity_embedding_stream
                        scv.pl.velocity_embedding_stream(
                            adata_dynamo,
                            basis=viz_basis,
                            color=color_col,
                            ax=axes[1],
                            show=False,
                            title=f"Velocity Stream ({viz_basis.upper()})"
                        )
                    except ImportError:
                        # Manual arrow plot if scvelo not available
                        vel_key = f'velocity_{viz_basis}'
                        if vel_key in adata_dynamo.obsm:
                            X_emb = adata_dynamo.obsm[f'X_{viz_basis}']
                            V_emb = adata_dynamo.obsm[vel_key]
                            axes[1].scatter(X_emb[:, 0], X_emb[:, 1], c='lightgray', s=5, alpha=0.5)
                            # Subsample for quiver plot
                            step = max(1, len(X_emb) // 500)
                            axes[1].quiver(
                                X_emb[::step, 0], X_emb[::step, 1],
                                V_emb[::step, 0], V_emb[::step, 1],
                                alpha=0.5
                            )
                            axes[1].set_title(f"Velocity Arrows ({viz_basis.upper()})")
                        else:
                            sc.pl.embedding(adata_dynamo, basis=viz_basis, color=color_col, ax=axes[1], show=False)
                            axes[1].set_title(f"Embedding ({viz_basis.upper()})")
                    except Exception as e:
                        # Fallback to just embedding
                        sc.pl.embedding(adata_dynamo, basis=viz_basis, color=color_col, ax=axes[1], show=False)
                        axes[1].set_title(f"Embedding ({viz_basis.upper()})")
                        st.info(f"Velocity stream visualization skipped: {e}")

                    plt.tight_layout()
                    st.pyplot(fig)
                    plt.close()

                except Exception as e:
                    st.warning(f"Could not create visualization: {e}")

                # Save and download
                st.subheader("Download")

                output_path = os.path.join(st.session_state.tfvelo_dynamo_temp_dir, "tfvelo_dynamo_result.h5ad")

                with st.spinner("Preparing download..."):
                    adata_dynamo.write_h5ad(output_path, compression="gzip")

                with open(output_path, "rb") as f:
                    st.download_button(
                        label="📥 Download Dynamo-compatible h5ad",
                        data=f.read(),
                        file_name="tfvelo_dynamo_result.h5ad",
                        mime="application/octet-stream",
                        type="primary"
                    )

                st.success("""
                ✅ **Conversion complete!**

                This file can be used in the **Dynamo Perturbation (v2)** app.

                Next steps:
                1. Download the h5ad from the button above
                2. Open the **Dynamo Perturbation (v2)** app
                3. Upload the downloaded file
                4. Run perturbation analysis
                """)

                # Store in session state for direct use
                st.session_state.tfvelo_dynamo_adata = adata_dynamo

            except Exception as e:
                st.error(f"Conversion failed: {str(e)}")
                import traceback
                st.code(traceback.format_exc())

    else:
        st.warning("⚠️ Required data not found. Please upload a valid TFvelo result file.")

else:
    st.info("👆 Please upload a TFvelo result file to begin.")

    # Show example workflow
    with st.expander("📖 Example Workflow"):
        st.markdown("""
        ### TFvelo → Dynamo Perturbation Workflow

        1. Run RNA velocity analysis in the **TFvelo app**
           - Download the h5ad file

        2. Convert using **this app (TFvelo to Dynamo)**
           - Upload TFvelo results
           - Build Vector Field
           - Download in Dynamo format

        3. Run perturbation analysis in the **Dynamo Perturbation (v2) app**
           - Upload the converted file
           - Execute gene perturbation simulation

        ### Technical Background

        - **TFvelo**: Velocity estimation based on TF-target relationships
        - **Dynamo Vector Field**: Reconstruction of continuous velocity field
        - **Jacobian**: Gene-gene interaction matrix
        - **Perturbation**: Perturbation effect prediction using Jacobian
        """)
